### ISSUE TITLE
Snakemake versioning leads to pulp dependency issue

### ISSUE THREAD

**Issue by ConnorChato** [Wytamma/snk#57]
Noticed that running a pipeline throws `AttributeError: module 'pulp' has no attribute 'list_solvers'` as the pulp devs recently renamed that method to `listSolvers()`. That pulp dependancy comes from snakemake and the devs have locked the pulp version ([Issue]( //github.com/snakemake/snakemake/issues/2607) worked in as of release 8.1.2). It also looks like pulp version is also locked at the conda level ([Issue is here](https://github.com/bioconda/bioconda-recipes/pull/45234)), but I don't believe this would take effect if snakemake is being installed through PyPi.

**Comment by Wytamma** [comment]
Thanks @ConnorChato! I've pinned pulp to <2.8 in [v0.18.0](https://github.com/Wytamma/snk/releases/tag/v0.18.0) of snk.
